// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: pkg/grpc/calc.proto

package calc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TaskInfo:
	//
	//	*GetTaskResponse_Task
	//	*GetTaskResponse_NoTask
	TaskInfo      isGetTaskResponse_TaskInfo `protobuf_oneof:"task_info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskResponse) GetTaskInfo() isGetTaskResponse_TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		if x, ok := x.TaskInfo.(*GetTaskResponse_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *GetTaskResponse) GetNoTask() *NoTaskAvailable {
	if x != nil {
		if x, ok := x.TaskInfo.(*GetTaskResponse_NoTask); ok {
			return x.NoTask
		}
	}
	return nil
}

type isGetTaskResponse_TaskInfo interface {
	isGetTaskResponse_TaskInfo()
}

type GetTaskResponse_Task struct {
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type GetTaskResponse_NoTask struct {
	NoTask *NoTaskAvailable `protobuf:"bytes,2,opt,name=no_task,json=noTask,proto3,oneof"`
}

func (*GetTaskResponse_Task) isGetTaskResponse_TaskInfo() {}

func (*GetTaskResponse_NoTask) isGetTaskResponse_TaskInfo() {}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1            float64                `protobuf:"fixed64,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2            float64                `protobuf:"fixed64,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation       string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTimeMs int32                  `protobuf:"varint,5,opt,name=operation_time_ms,json=operationTimeMs,proto3" json:"operation_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetOperationTimeMs() int32 {
	if x != nil {
		return x.OperationTimeMs
	}
	return 0
}

type NoTaskAvailable struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RetryAfterSeconds int32                  `protobuf:"varint,1,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NoTaskAvailable) Reset() {
	*x = NoTaskAvailable{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoTaskAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoTaskAvailable) ProtoMessage() {}

func (x *NoTaskAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoTaskAvailable.ProtoReflect.Descriptor instead.
func (*NoTaskAvailable) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{3}
}

func (x *NoTaskAvailable) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type SubmitResultRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to ResultStatus:
	//
	//	*SubmitResultRequest_Result
	//	*SubmitResultRequest_Error
	ResultStatus  isSubmitResultRequest_ResultStatus `protobuf_oneof:"result_status"`
	WorkerId      string                             `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitResultRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SubmitResultRequest) GetResultStatus() isSubmitResultRequest_ResultStatus {
	if x != nil {
		return x.ResultStatus
	}
	return nil
}

func (x *SubmitResultRequest) GetResult() float64 {
	if x != nil {
		if x, ok := x.ResultStatus.(*SubmitResultRequest_Result); ok {
			return x.Result
		}
	}
	return 0
}

func (x *SubmitResultRequest) GetError() *TaskError {
	if x != nil {
		if x, ok := x.ResultStatus.(*SubmitResultRequest_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *SubmitResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type isSubmitResultRequest_ResultStatus interface {
	isSubmitResultRequest_ResultStatus()
}

type SubmitResultRequest_Result struct {
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3,oneof"`
}

type SubmitResultRequest_Error struct {
	Error *TaskError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*SubmitResultRequest_Result) isSubmitResultRequest_ResultStatus() {}

func (*SubmitResultRequest_Error) isSubmitResultRequest_ResultStatus() {}

type TaskError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskError) Reset() {
	*x = TaskError{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskError) ProtoMessage() {}

func (x *TaskError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskError.ProtoReflect.Descriptor instead.
func (*TaskError) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{5}
}

func (x *TaskError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_pkg_grpc_calc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_calc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_calc_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_pkg_grpc_calc_proto protoreflect.FileDescriptor

const file_pkg_grpc_calc_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/grpc/calc.proto\x12\x04calc\"-\n" +
	"\x0eGetTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"r\n" +
	"\x0fGetTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".calc.TaskH\x00R\x04task\x120\n" +
	"\ano_task\x18\x02 \x01(\v2\x15.calc.NoTaskAvailableH\x00R\x06noTaskB\v\n" +
	"\ttask_info\"\x88\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\x01R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\x01R\x04arg2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12*\n" +
	"\x11operation_time_ms\x18\x05 \x01(\x05R\x0foperationTimeMs\"A\n" +
	"\x0fNoTaskAvailable\x12.\n" +
	"\x13retry_after_seconds\x18\x01 \x01(\x05R\x11retryAfterSeconds\"\x9f\x01\n" +
	"\x13SubmitResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x18\n" +
	"\x06result\x18\x02 \x01(\x01H\x00R\x06result\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.calc.TaskErrorH\x00R\x05error\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerIdB\x0f\n" +
	"\rresult_status\"%\n" +
	"\tTaskError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x14SubmitResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\x92\x01\n" +
	"\x11CalcWorkerService\x126\n" +
	"\aGetTask\x12\x14.calc.GetTaskRequest\x1a\x15.calc.GetTaskResponse\x12E\n" +
	"\fSubmitResult\x12\x19.calc.SubmitResultRequest\x1a\x1a.calc.SubmitResultResponseB\x1bZ\x19internal/worker/grpc/calcb\x06proto3"

var (
	file_pkg_grpc_calc_proto_rawDescOnce sync.Once
	file_pkg_grpc_calc_proto_rawDescData []byte
)

func file_pkg_grpc_calc_proto_rawDescGZIP() []byte {
	file_pkg_grpc_calc_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_calc_proto_rawDesc), len(file_pkg_grpc_calc_proto_rawDesc)))
	})
	return file_pkg_grpc_calc_proto_rawDescData
}

var file_pkg_grpc_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_grpc_calc_proto_goTypes = []any{
	(*GetTaskRequest)(nil),       // 0: calc.GetTaskRequest
	(*GetTaskResponse)(nil),      // 1: calc.GetTaskResponse
	(*Task)(nil),                 // 2: calc.Task
	(*NoTaskAvailable)(nil),      // 3: calc.NoTaskAvailable
	(*SubmitResultRequest)(nil),  // 4: calc.SubmitResultRequest
	(*TaskError)(nil),            // 5: calc.TaskError
	(*SubmitResultResponse)(nil), // 6: calc.SubmitResultResponse
}
var file_pkg_grpc_calc_proto_depIdxs = []int32{
	2, // 0: calc.GetTaskResponse.task:type_name -> calc.Task
	3, // 1: calc.GetTaskResponse.no_task:type_name -> calc.NoTaskAvailable
	5, // 2: calc.SubmitResultRequest.error:type_name -> calc.TaskError
	0, // 3: calc.CalcWorkerService.GetTask:input_type -> calc.GetTaskRequest
	4, // 4: calc.CalcWorkerService.SubmitResult:input_type -> calc.SubmitResultRequest
	1, // 5: calc.CalcWorkerService.GetTask:output_type -> calc.GetTaskResponse
	6, // 6: calc.CalcWorkerService.SubmitResult:output_type -> calc.SubmitResultResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_calc_proto_init() }
func file_pkg_grpc_calc_proto_init() {
	if File_pkg_grpc_calc_proto != nil {
		return
	}
	file_pkg_grpc_calc_proto_msgTypes[1].OneofWrappers = []any{
		(*GetTaskResponse_Task)(nil),
		(*GetTaskResponse_NoTask)(nil),
	}
	file_pkg_grpc_calc_proto_msgTypes[4].OneofWrappers = []any{
		(*SubmitResultRequest_Result)(nil),
		(*SubmitResultRequest_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_calc_proto_rawDesc), len(file_pkg_grpc_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_calc_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_calc_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_calc_proto_msgTypes,
	}.Build()
	File_pkg_grpc_calc_proto = out.File
	file_pkg_grpc_calc_proto_goTypes = nil
	file_pkg_grpc_calc_proto_depIdxs = nil
}
